/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_zlcompress_ZLCompress */

#ifndef _Included_com_github_zlcompress_ZLCompress
#define _Included_com_github_zlcompress_ZLCompress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zlcompress_ZLCompress
 * Method:    compressBitmap
 * Signature: (Ljava/lang/Object;III[BZ)I
 */
//Java_com_github_zlcompress_ZLCompress_compressBitmap
JNIEXPORT jint JNICALL Java_com_github_zlcompress_ZLCompress_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
